# Generated by Django 3.0.5 on 2020-04-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annieapp', '0003_auto_20200406_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
