# Generated by Django 3.0.5 on 2020-04-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annieapp', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
