# Generated by Django 3.0.5 on 2020-04-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annieapp', '0006_category_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
