# Generated by Django 3.0.5 on 2020-04-11 05:20

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annieapp', '0008_auto_20200410_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Thương hiệu', 'verbose_name_plural': 'Thương hiệu'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Nhóm sản phẩm', 'verbose_name_plural': 'Nhóm sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Danh sách đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Danh sách sản phẩm'},
        ),
        migrations.AddField(
            model_name='banner',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '808x1920', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(help_text='Kích thước cao x rộng ~ 808 x 1920px', max_length=50),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên thương hiệu (Brand)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên nhóm sản phẩm (Category)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Đã xác nhận'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Được tạo lúc'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Đã thanh toán'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(help_text='Gọi điện để xác nhận đơn hàng', max_length=100, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(max_length=60, verbose_name='Dạng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Chỉnh sửa lúc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(help_text='Nếu chưa có nhấn dấu + để tạo', on_delete=django.db.models.deletion.CASCADE, to='annieapp.Brand', verbose_name='Thương hiệu (Brand)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Nếu chưa có nhấn dấu + để tạo', on_delete=django.db.models.deletion.CASCADE, to='annieapp.Category', verbose_name='Phân loại sản phẩm (Category)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_product',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm bán chạy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new_product',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm mới'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=models.ImageField(blank=True, help_text='Ảnh và chữ được tạo trong photoshop, chiều ngang 1000, không giới hạn chiều dài', null=True, upload_to='images/', verbose_name='Ảnh chi tiết sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(help_text='Chiều cao và rộng bằng nhau VD:1000x1000 (Lưu ý: Ảnh này là ảnh đại diện sản phẩm ngoài trang chủ)', upload_to='images/', verbose_name='Ảnh sản phẩm 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(blank=True, help_text='Chiều cao và rộng bằng nhau VD:1000x1000 ', null=True, upload_to='images/', verbose_name='Ảnh sản phẩm 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img3',
            field=models.ImageField(blank=True, help_text='Chiều cao và rộng bằng nhau VD:1000x1000', null=True, upload_to='images/', verbose_name='Ảnh sản phẩm 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_off',
            field=models.IntegerField(default=0, help_text='Chữ số, không có dấu %', verbose_name='Giảm giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_price',
            field=models.IntegerField(default=0, verbose_name='Giá gốc'),
        ),
    ]
