# Generated by Django 3.0.5 on 2020-04-11 05:48

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annieapp', '0009_auto_20200411_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cropping_img_1',
            field=image_cropping.fields.ImageRatioField('product_img1', '1x1', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping img 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='cropping_img_2',
            field=image_cropping.fields.ImageRatioField('product_img2', '1x1', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping img 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='cropping_img_3',
            field=image_cropping.fields.ImageRatioField('product_img3', '1x1', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping img 3'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('banner_img', '1920x808', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(help_text='(Lưu ý: Ảnh này là ảnh đại diện sản phẩm ngoài trang chủ)', upload_to='images/', verbose_name='Ảnh sản phẩm 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Ảnh sản phẩm 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Ảnh sản phẩm 3'),
        ),
    ]
