# Generated by Django 3.0.5 on 2020-04-11 10:55

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annieapp', '0010_auto_20200411_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cropping_img_1',
            field=image_cropping.fields.ImageRatioField('product_img1', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Chỉnh sửa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_img_2',
            field=image_cropping.fields.ImageRatioField('product_img2', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Chỉnh sửa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_img_3',
            field=image_cropping.fields.ImageRatioField('product_img3', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Chỉnh sửa'),
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Màu sắc, lựa chọn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annieapp.Product')),
            ],
        ),
    ]
