# Generated by Django 3.0.5 on 2020-05-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annieapp', '0015_auto_20200415_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False, verbose_name='Đã Hủy'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Đang giao hàng'),
        ),
    ]
